example_1:
  description: Verifies and installs Automation Toolchain components (DO, AS3) on a local BIG-IP and then configures AS3 from a local declaration file.
  runtime_config:
example_2:
  description: Verifies and installs DO and myIlxApp RPMs from local directories and configures DO from a local declaration file. Install operations with an extensionUrl value that points to a local file stored on BIGIP system.
  runtime_config:
example_3:
  description: Installs DO and AS3 on a local BIG-IP and renders the Azure service principal secret into an AS3 declaration downloaded from a URL.
  runtime_config:
example_4:
  description: Renders secret referenced within DO declaration to configure the admin password on a BIG-IP device in AWS.
  runtime_config:
example_5:
  description: Renders secret referenced within DO declaration to configure the admin password on a BIG-IP device in GCP.
  runtime_config:
example_6:
  description: Replaces variables used within DO declaration with properties from instance metadata to configure hostname and self IP addresses on BIGIP device.
  runtime_config:
example_7:
  description: Installs AS3 and DO and uses an inline AS3 declaration to setup the BIG-IP.
  runtime_config:
example_8:
  description: Using runtime parameters with inline Automation Toolchain declarations.
  runtime_config:
example_9:
  description: Using custom pre-onboard and post-onboard commands.
  runtime_config:
example_10:
  description: Sending a customized webhook on completion.
  runtime_config:
example_11:
  description: 'Overrides default certificate validation/verification using the verifyTls parameter. The following attributes support verifyTls: pre_onboard_enabled, post_onboard_enabled, extension_packages.install_operations, extension_services.service_operations, and post_hook.'
  runtime_config:
example_12:
  description: Licenses BIG-IP device using BIG-IQ utility offering and authenticating with credentials stored in Azure KeyVault.
  runtime_config:
